"""Pygments lexers that render noweb chunk references everywhere.

These lexers wrap an ordinary Pygments lexer and turn spans
delimited by U+E000 and U+E001 into ``Token.Escape``, which the
LaTeX formatter copies into its output verbatim.  Unlike minted's
``escapeinside``, this also works inside strings and comments, so
noweb chunk references in Python docstrings keep their hyperlinks.
The delimiters are Unicode private-use characters that never occur
in real code; the input is generated by the tominted filter.

Use with minted as ``\\begin{minted}{noweb_lexer.py:NowebPythonLexer}``
(see nowebfilters(7) for the latexminted security setup).
"""

from pygments.formatters.latex import LatexEmbeddedLexer
from pygments.lexers import get_all_lexers, get_lexer_by_name

ESCAPE_LEFT = "\ue000"
ESCAPE_RIGHT = "\ue001"


class NowebEscapeLexer(LatexEmbeddedLexer):
    """Wrap ``base_lexer``, escaping U+E000...U+E001 spans anywhere."""

    base_lexer = "text"

    def __init__(self, **options):
        super().__init__(ESCAPE_LEFT, ESCAPE_RIGHT,
                         get_lexer_by_name(self.base_lexer, **options),
                         **options)

    def _find_safe_escape_tokens(self, text):
        # Unlike LatexEmbeddedLexer, process escapes everywhere,
        # including inside strings and comments.
        yield from self._find_escape_tokens(text)


def _class_name(alias):
    """Return the wrapper class name for ``alias``.

    Must compute the same name as the tominted filter's
    ``lexer_class``: non-alphanumeric runs are word breaks and
    every word is capitalized.
    """
    words = "".join(c if c.isalnum() else " " for c in alias).split()
    return "Noweb" + "".join(w.capitalize() for w in words) + "Lexer"


for _, _aliases, _, _ in get_all_lexers():
    for _alias in _aliases:
        _name = _class_name(_alias)
        if _name not in globals():
            globals()[_name] = type(_name, (NowebEscapeLexer,),
                                    {"base_lexer": _alias})
