.TH CPIF 1 "local \- 2/26/93"
.SH NAME
cpif \- selectively update files
.SH SYNOPSIS
.B cpif
[\fB-eq\fP|\fB-ne\fP] file ...
.SH DESCRIPTION
.I cpif
is an auxiliary tool for use with 
.I notangle(1)
and
.I make(1).
.I cpif
compares its standard input to each of the named files,
overwriting the file if the comparison succeeds or if
the named file does not exist.
If neither
.B -eq
or 
.B -ne
is specified, the default is
.B -ne.
Typical usage is in the following default rule, suitable for use in a Makefile.
.br
 .nw.h: ; notangle -Rheader $*.nw | cpif $*.h
.br
.SH SEE ALSO
.I notangle(1)
.SH AUTHOR
Norman Ramsey, Bellcore.
Internet address \fBnorman@bellcore.com\fP.
