.TH NOWEB 1 "10/40/2008"
.SH NAME
nuweb2noweb \- convert nuweb files to noweb form
.SH SYNOPSIS
.B nuweb2noweb
file ...
.SH DESCRIPTION
.I Nuweb2noweb
converts a file or files in 
.I nuweb
format to
.I noweb
format, writing the results on standard output.
Input is from the file(s) named on the command line.
.SH SEE ALSO
.PP
.IR noweb (1),
.IR nuweb (1)
.SH VERSION
This man page is from 
.I noweb
version 2.12.
.SH AUTHOR
Norman Ramsey, Tufts University.
Internet address \fBNorman.Ramsey@tufts.edu\fP.
.br
Noweb home page at \fBhttp://www.cs.tufts.edu/~nr/noweb\fP.

