#!/bin/sh
#
# Copyright 1991 by Norman Ramsey.  All rights reserved.
# See file COPYRIGHT for more information.
# set -x
LIB=|LIBDIR|
opt= arg=
for i do
	case $i in
        -ml|-m3|-awk|-c|-w[0-9][0-9]*) ;; # deliberately ignore nountangle args
	-*) opt="$opt '$i'" ;;
	*)  arg="$arg '$i'" ;;
	esac
done
eval "$LIB/markup $arg | $LIB/nt $opt"
