#!/bin/sh
nawk '
/^@file / {
#  if (file) printf "EndOf%s\n", file
#  file = substr($0,7);
#  printf "diff %s - <<'"'EndOf%s'"'\n", file, file
}
function unpend() { # nasty stuff to avoid adding space after @
  if (doc_pending) {
    printf "@ "
    doc_pending = 0;
  }
}

END { 
  unpend()
#  if (file) printf "EndOf%s\n", file
}

/^@begin docs 0$/ { next }
/^@begin docs / { unpend() ; doc_pending=1 }
/^@end docs / { }

/^@begin code / { unpend() }
/^@defn / { unpend() ; printf "<<%s>>=\n", substr($0,7) }

/^@text $/ {next}
/^@text / { 
  unpend()
  gsub("<<", "@<<");
  gsub(">>", "@>>");
  printf "%s", substr($0,7) 
}
/^@quote$/ { 
  unpend()
  printf("[[");
}
/^@endquote$/ { 
  printf("]]");
}

/^@nl$/ { if (doc_pending) {
            printf("@");
	    doc_pending = 0;
          }
           printf "\n" 
        }

/^@use / { printf "<<%s>>", substr($0,6) }' $*
