#!/bin/sh
if [ $# -eq 0 ]; then set all install; fi  # "$@" breaks make for empty args
make CC=gcc CFLAGS=-DTEMPNAM BIN=/homes/nr/pkg/noweb/bin LIB=/homes/nr/pkg/noweb/lib MAN=/homes/nr/pkg/noweb/man TEXINPUTS=/homes/nr/pkg/tex/inputs "$@"
