#!/bin/sh
if [ $# -eq 0 ]; then set all install; fi  # "$@" breaks make for empty args
/usr/bin/make CC=gcc CFLAGS="-ansi -pedantic -O -Wall -Werror" LIBSRC=icon BIN=/usr/local/noweb/bin LIB=/usr/local/noweb/lib MAN=/usr/local/noweb/man TEXINPUTS=/usr/share/texmf/tex/plain/misc ELISP=$HOME/emacs "$@"
