#!/bin/sh
if [ $# -eq 0 ]; then set all install; fi  # "$@" breaks make for empty args
/usr/bin/make CC="lcc -A" CFLAGS=-DTEMPNAM LIBSRC=icon BIN=/usr/local/noweb/bin LIB=/usr/local/noweb/lib MAN=/usr/local/noweb/man TEXINPUTS=/usr/share/texmf/tex/latex/local ELISP=$HOME/emacs "$@"
